# Generated by Django 4.2.7 on 2025-11-02 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_analysisrequest_moderator_analysisrequest_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisartifact',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Вес артефакта в анализе (от 0 до 1)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Вес'),
        ),
    ]
